minimumReleaseAgeExclude:
  - '@navikt/*'

onlyBuiltDependencies:
  - '@swc/core'
  - cypress
  - es5-ext
  - esbuild
  - msw
  - protobufjs

overrides:
  # ajv@<8.18.0: '>=8.18.0'
  diff@<8.0.3: '>=8.0.3'
  minimatch@<10.2.1: '>=10.2.1'
