minimumReleaseAgeExclude:
  - '@navikt/aksel-icons@8.13.0'
  - '@navikt/ds-css@8.13.0'
  - '@navikt/ds-react@8.13.0'
  - '@navikt/ds-tokens@8.13.0'
  - js-yaml@4.1.2
  - '@opentelemetry/core@2.8.0'

onlyBuiltDependencies:
  - '@swc/core'
  - cypress
  - es5-ext
  - esbuild
  - msw
  - protobufjs

updateConfig:
  ignoreDependencies:
    - '@types/node'

allowBuilds:
  cypress: true
  es5-ext: false
  esbuild: true
  msw: true
  protobufjs: false

overrides:
  '@opentelemetry/core@<2.8.0': ^2.8.0
  js-yaml@<=4.1.1: ^4.1.2
