minimumReleaseAgeExclude:
  - '@navikt/*'

onlyBuiltDependencies:
  - '@swc/core'
  - cypress
  - es5-ext
  - esbuild
  - msw
  - protobufjs

updateConfig:
  ignoreDependencies:
    - '@types/node'

allowBuilds:
  cypress: true
  es5-ext: false
  esbuild: true
  msw: true
  protobufjs: false
