minimumReleaseAgeExclude:
  - '@navikt/*'
  - protobufjs@8.0.2

onlyBuiltDependencies:
  - '@swc/core'
  - cypress
  - es5-ext
  - esbuild
  - msw
  - protobufjs

updateConfig:
  ignoreDependencies:
    - '@types/node'

allowBuilds:
  cypress: true
  es5-ext: false
  esbuild: true
  msw: true
  protobufjs: false

overrides:
  protobufjs@>=8.0.0 <=8.0.1: ^8.0.2
