export const Enhet = {
  IT_AVDELINGEN: '2970',

  NAV_HJELPEMIDDELSENTRAL_AGDER: '4710',
  /**
   * @deprecated nedlagt
   */
  NAV_HJELPEMIDDELSENTRAL_AGDER_ARENDAL: '4709',
  NAV_HJELPEMIDDELSENTRAL_AKERSHUS: '4702',
  NAV_HJELPEMIDDELSENTRAL_INNLANDET_ELVERUM: '4704',
  NAV_HJELPEMIDDELSENTRAL_INNLANDET_GJØVIK: '4705',
  NAV_HJELPEMIDDELSENTRAL_MØRE_OG_ROMSDAL: '4715',
  NAV_HJELPEMIDDELSENTRAL_NORDLAND: '4718',
  NAV_HJELPEMIDDELSENTRAL_OSLO: '4703',
  NAV_HJELPEMIDDELSENTRAL_ROGALAND: '4711',
  NAV_HJELPEMIDDELSENTRAL_TROMS_OG_FINNMARK: '4719',
  /**
   * @deprecated nedlagt
   */
  NAV_HJELPEMIDDELSENTRAL_TROMS_OG_FINNMARK_LAKSELV: '4720',
  NAV_HJELPEMIDDELSENTRAL_TRØNDELAG: '4716',
  NAV_HJELPEMIDDELSENTRAL_VESTFOLD_OG_TELEMARK: '4707',
  /**
   * @deprecated nedlagt
   */
  NAV_HJELPEMIDDELSENTRAL_VESTFOLD_OG_TELEMARK_SKIEN: '4708',
  NAV_HJELPEMIDDELSENTRAL_VESTLAND_BERGEN: '4712',
  NAV_HJELPEMIDDELSENTRAL_VESTLAND_FØRDE: '4714',
  NAV_HJELPEMIDDELSENTRAL_VEST_VIKEN: '4706',
  NAV_HJELPEMIDDELSENTRAL_ØST_VIKEN: '4701',

  NAV_VIKAFOSSEN: '2103',
} as const

export type EnhetType = typeof Enhet
export type EnhetsnummerType = EnhetType[keyof EnhetType]
