// TODO: Rydde opp i disse og ikke kall dem noe som har med plassering i UI å gjøre

export enum VenstrekolonneTabs {
  BEHOVSMELDINGSINFO = 'BEHOVSMELDINGSINFO',
  SAKSOVERSIKT = 'SAKSOVERSIKT',
  DOKUMENTOVERSIKT = 'DOKUMENTOVERSIKT',
  SAKSHISTORIKK = 'SAKSHISTORIKK',
  HJELPEMIDDELOVERSIKT = 'HJELPEMIDDELOVERSIKT',
}

export enum HøyrekolonneTabs {
  NOTATER = 'NOTATER',
  BREV = 'BREV',
  BEHANDLING = 'BEHANDLING',
}

export enum SidebarValg {
  SAKSHISTORIKK = 'SAKSHISTORIKK',
  HJELPEMIDDELOVERSIKT = 'HJELPEMIDDELOVERSIKT',
  NOTATER = 'NOTATER',
}
