apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hotsak-frontend
    team: teamdigihot
  name: hotsak-frontend
  namespace: teamdigihot
  annotations:
    snorlax.nais.io/enabled: "true"
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - https://hotsak.intern.dev.nav.no
    - https://hotsak.ansatt.dev.nav.no
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  replicas:
    max: 1
    min: 1
  accessPolicy:
    inbound:
      rules:
        - application: azure-token-generator
          namespace: aura
          cluster: dev-gcp
    outbound:
      rules:
        - application: hm-saksbehandling
        - application: hm-grunndata-search
        - application: hm-grunndata-alternativprodukter
        - application: hm-brille-api
        - application: hm-mocks
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "b9340050-ccb5-4de7-9d96-0fb2d9fb38eb"
    sidecar:
      enabled: true
      autoLogin: false
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 10m
      memory: 256Mi
  envFrom:
    - secret: hm-saksbehandling
  env:
    - name: PORT
      value: "3000"
    - name: HOTSAK_API_URL
      value: http://hm-saksbehandling.teamdigihot.svc.cluster.local
    - name: HOTSAK_API_SCOPE
      value: api://dev-gcp.teamdigihot.hm-saksbehandling/.default
    - name: GRUNNDATA_API_URL
      value: http://hm-grunndata-search.teamdigihot.svc.cluster.local
    - name: ALTERNATIVPRODUKTER_API_URL
      value: http://hm-grunndata-alternativprodukter.teamdigihot.svc.cluster.local
    - name: BRILLE_API_URL
      value: http://hm-brille-api.teamdigihot.svc.cluster.local
    - name: USE_MSW
      value: "false"
    - name: USE_MSW_GRUNNDATA
      value: "false"
    - name: USE_MSW_ALTERNATIVPRODUKTER
      value: "false"
    - name: GIT_COMMIT
      value: {{commit}}
    - name: FARO_URL
      value: https://telemetry.ekstern.dev.nav.no/collect
    - name: IMAGE_PROXY_URL
      value: https://finnhjelpemiddel.intern.dev.nav.no/imageproxy/400d
    - name: UMAMI_WEBSITE_ID
      value: 6f5bb9df-1dfe-4d77-aa40-9cd5d88c7b24
    - name: UMAMI_ENABLED
      value: "true"
