apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hotsak-frontend-labs
    team: teamdigihot
  name: hotsak-frontend-labs
  namespace: teamdigihot
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - https://hotsak.ekstern.dev.nav.no
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    max: 1
    min: 1
  accessPolicy:
    outbound:
      rules:
        - application: hm-grunndata-search
        - application: hm-grunndata-alternativprodukter
  azure:
    application:
      enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 10m
      memory: 256Mi
  envFrom:
    - secret: hm-saksbehandling
  env:
    - name: PORT
      value: "3000"
    - name: HOTSAK_API_URL
      value: http://hm-saksbehandling.teamdigihot.svc.cluster.local
    - name: HOTSAK_API_SCOPE
      value: api://dev-gcp.teamdigihot.hm-saksbehandling/.default
    - name: GRUNNDATA_API_URL
      value: http://hm-grunndata-search.teamdigihot.svc.cluster.local
    - name: ALTERNATIVPRODUKTER_API_URL
      value: http://hm-grunndata-alternativprodukter.teamdigihot.svc.cluster.local
    - name: BRILLE_API_URL
      value: http://hm-brille-api.teamdigihot.svc.cluster.local
    - name: USE_MSW
      value: "true"
    - name: USE_MSW_GRUNNDATA
      value: "true"
    - name: USE_MSW_ALTERNATIVPRODUKTER
      value: "true"
    - name: GIT_COMMIT
      value: {{commit}}
    - name: FARO_URL
      value: https://telemetry.ekstern.dev.nav.no/collect
    - name: IMAGE_PROXY_URL
      value: https://finnhjelpemiddel.nav.no/imageproxy/400d
    - name: UMAMI_WEBSITE_ID
      value: ""
    - name: UMAMI_ENABLED
      value: "false"
