apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hotsak-frontend
    team: teamdigihot
  name: hotsak-frontend
  namespace: teamdigihot
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - https://hotsak.intern.nav.no
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    max: 6
    min: 2
  accessPolicy:
    outbound:
      rules:
        - application: hm-saksbehandling
        - application: hm-brille-api
        - application: hm-grunndata-search
        - application: heit-krukka
        - application: hm-grunndata-alternativprodukter
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "88956569-f23d-455c-ace4-001b56e94602"
          - id: "2f632b40-4730-4692-9c7c-fb744e2d33e1"
    sidecar:
      enabled: true
      autoLogin: false
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  envFrom:
    - secret: hm-saksbehandling
  env:
    - name: API_URL
      value: http://hm-saksbehandling.teamdigihot.svc.cluster.local
    - name: FINN_HJELPEMIDDEL_API_URL
      value: http://hm-grunndata-search.teamdigihot.svc.cluster.local
    - name: FINN_ALTERNATIV_PRODUKT_API_URL
      value: http://hm-grunndata-alternativprodukter.teamdigihot.svc.cluster.local
    - name: BRILLEKALKULATOR_API_URL
      value: http://hm-brille-api.teamdigihot.svc.cluster.local
    - name: PORT
      value: "3000"
    - name: CLIENT_ID_HOTSAK_API
      value: api://prod-gcp.teamdigihot.hm-saksbehandling/.default
    - name: USE_MSW
      value: "false"
    - name: GIT_COMMIT
      value: {{commit}}
    - name: FARO_URL
      value: https://telemetry.nav.no/collect
    - name: AMPLITUDE_API_KEY
      value: 10798841ebeba333b8ece6c046322d76
    - name: AMPLITUDE_SERVER_URL
      value: https://amplitude.nav.no/collect-auto
    - name: IMAGE_PROXY_URL
      value: https://finnhjelpemiddel.nav.no/imageproxy/400d
