apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hotsak-frontend
    team: teamdigihot
  name: hotsak-frontend
  namespace: teamdigihot
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - https://hotsak.intern.nav.no
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    max: 6
    min: 2
  accessPolicy:
    outbound:
      rules:
        - application: hm-saksbehandling
        - application: hm-grunndata-search
        - application: hm-grunndata-alternativprodukter
        - application: hm-brille-api
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "88956569-f23d-455c-ace4-001b56e94602"
          - id: "2f632b40-4730-4692-9c7c-fb744e2d33e1"
    sidecar:
      enabled: true
      autoLogin: false
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  envFrom:
    - secret: hm-saksbehandling
  env:
    - name: PORT
      value: "3000"
    - name: HOTSAK_API_URL
      value: http://hm-saksbehandling.teamdigihot.svc.cluster.local
    - name: HOTSAK_API_SCOPE
      value: api://prod-gcp.teamdigihot.hm-saksbehandling/.default
    - name: GRUNNDATA_API_URL
      value: http://hm-grunndata-search.teamdigihot.svc.cluster.local
    - name: ALTERNATIVPRODUKTER_API_URL
      value: http://hm-grunndata-alternativprodukter.teamdigihot.svc.cluster.local
    - name: BRILLE_API_URL
      value: http://hm-brille-api.teamdigihot.svc.cluster.local
    - name: USE_MSW
      value: "false"
    - name: USE_MSW_GRUNNDATA
      value: "false"
    - name: USE_MSW_ALTERNATIVPRODUKTER
      value: "false"
    - name: GIT_COMMIT
      value: {{commit}}
    - name: FARO_URL
      value: https://telemetry.nav.no/collect
    - name: IMAGE_PROXY_URL
      value: https://finnhjelpemiddel.nav.no/imageproxy/400d
    - name: UMAMI_WEBSITE_ID
      value: 97bc2b63-e714-42e8-b364-39d59e022039
    - name: UMAMI_ENABLED
      value: "false"
