/**
 * @see [Tema - Team Dokumentløsninger Sysdok - Confluence](https://confluence.adeo.no/x/_NHbEg)
 */
export const Tema = {
  AAP: 'Arbeidsavklaringspenger',
  AAR: 'Aa-registeret',
  AGR: 'Ajourhold - grunnopplysninger',
  AKT: 'Aktivitetsplan med dialoger',
  ARP: 'Arbeidsrådgivning - psykologtester',
  ARS: 'Arbeidsrådgivning - skjermet',
  BAR: 'Barnetrygd',
  BBF: 'Barnebortføring',
  BID: 'Bidrag',
  BIL: 'Bil',
  DAG: 'Dagpenger',
  ENF: 'Enslig mor eller far',
  ERS: 'Erstatning',
  EYB: 'Barnepensjon',
  EYO: 'Omstillingsstønad',
  FAR: 'Foreldreskap',
  FEI: 'Feilutbetaling',
  FIP: 'Fiskerpensjon',
  FOR: 'Foreldre- og svangerskapspenger',
  FOS: 'Forsikring',
  FRI: 'Kompensasjon for selvstendig næringsdrivende/frilansere',
  FUL: 'Fullmakt',
  GEN: 'Generell',
  GRA: 'Gravferdsstønad',
  GRU: 'Grunn- og hjelpestønad',
  HEL: 'Helsetjenester og ortopediske hjelpemidler',
  HJE: 'Hjelpemidler',
  IAR: 'Inkluderende arbeidsliv',
  IND: 'Tiltakspenger',
  KLL: 'Klage - lønnsgaranti',
  KON: 'Kontantstøtte',
  KTA: 'Kontroll - anmeldelse',
  KTR: 'Kontroll',
  MED: 'Medlemskap',
  MOB: 'Mobilitetsfremmende stønad',
  OLJ: 'Oljepionerene',
  OMS: 'Omsorgspenger, pleiepenger og opplæringspenger',
  OPA: 'Oppfølging - arbeidsgiver',
  OPP: 'Oppfølging',
  PAI: 'Innsyn',
  PEN: 'Pensjon',
  PER: 'Permittering og masseoppsigelser',
  POI: 'Innsyn etter personopplysningsloven',
  REH: 'Rehabiliteringspenger',
  REK: 'Rekruttering',
  RPO: 'Retting av personopplysninger',
  RVE: 'Rettferdsvederlag',
  SAA: 'Sanksjon - Arbeidsgiver',
  SAK: 'Sakskostnader',
  SAP: 'Sanksjon - person',
  SER: 'Serviceklager',
  STO: 'Regnskap/utbetaling/årsoppgave',
  SUP: 'Supplerende stønad',
  SYK: 'Sykepenger',
  SYM: 'Sykmelding',
  TIL: 'Tiltak',
  TRK: 'Trekkhåndtering',
  TRY: 'Trygdeavgift',
  TSO: 'Tilleggsstønad',
  TSR: 'Tilleggsstønad - arbeidssøkere',
  UFM: 'Unntak fra medlemskap',
  UFO: 'Uføretrygd',
  UKJ: 'Ukjent',
  UNG: 'Ungdomsprogramytelsen',
  VEN: 'Ventelønn',
  YRA: 'Yrkesrettet attføring',
  YRK: 'Yrkesskade og menerstatning',
} as const
export type Tema = keyof typeof Tema

/**
 * @see [opprettJournalpost - Team Dokumentløsninger Sysdok - Confluence](https://confluence.adeo.no/x/FUutEg)
 */
export const Fagsaksystem = {
  AO01: 'Arena',
  AO11: 'Grisen',
  ARBEIDSOPPFOLGING: 'Arbeidsoppfølging',
  BA: 'Barnetrygd',
  BARNEBRILLER: 'Barnebriller',
  BISYS: 'BISYS',
  DAGPENGER: 'Dagpenger',
  EF: 'Enslig forsørger',
  EY: 'Etterlatteytelser',
  FIA: 'FIA',
  FS36: 'Foreldrepengeløsningen',
  FS38: 'Melosys',
  HELT: 'Helsetjenester',
  HJELPEMIDLER: 'Hotsak',
  IT01: 'Infotrygd',
  KELVIN: 'AAP',
  KOMPYS: 'Yrkesskade',
  KONT: 'Kontantstøtte',
  K9: 'Sykdom i familien',
  NEESSI: 'NEESSI',
  OB36: 'UR',
  OEBS: 'OEBS',
  OMSORGSPENGER: 'Omsorgspenger',
  PP01: 'Pesys',
  SPEIL: 'Fagsystem sykepenger',
  SUPERHELT: 'Fagsystem for diverse hjelpemidler',
  SUPSTONAD: 'Supplerende Stønad',
  TILLEGGSSTONADER: 'Tilleggsstønader',
  TILTAKSADMINISTRASJON: 'Tiltaksadministrasjon',
  TILTAKSPENGER: 'Tiltakspenger',
  UFM: 'Unntak fra medlemskap',
  UNG_SAK: 'Fagsystem for å saksbehandling av ungdomsprogramytelsen',
  REMEDY: 'Identstyring',
} as const
export type Fagsaksystem = keyof typeof Fagsaksystem
