export enum VenstrekolonneTabs {
  BEHOVSMELDINGSINFO = 'BEHOVSMELDINGSINFO',
  SAKSOVERSIKT = 'SAKSOVERSIKT',
  DOKUMENTOVERSIKT = 'DOKUMENTOVERSIKT',
  SAKSHISTORIKK = 'SAKSHISTORIKK',
  HJELPEMIDDELOVERSIKT = 'HJELPEMIDDELOVERSIKT',
}

export enum HøyrekolonneTabs {
  NOTATER = 'NOTATER',
  BREV = 'BREV',
  BEHANDLING = 'BEHANDLING',
}
