name: Bygg, deploy til dev-gcp og lag release

on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'
    branches:
      - TheDarkside

jobs:
  build:
    name: Bygg
    permissions:
      packages: write
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      docker_image: ${{ steps.docker-build-push.outputs.image }}
      version_tag: ${{ steps.version-tag.outputs.VERSION_TAG}}

    steps:
      - name: Sjekk ut koden
        uses: actions/checkout@v4

      - name: Før deploy
        uses: navikt/digihot-deploy/actions/pre-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bygg og push Docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: teamdigihot
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          tag: ${{ env.VERSION_TAG }}
          build_secrets: NODE_AUTH_TOKEN=${{ secrets.READER_TOKEN }}


  deploy-labs:
    name: Deploy til labs-gcp
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
      id-token: write
    timeout-minutes: 15

    steps:
      - name: Sjekk ut koden
        uses: actions/checkout@v4

      - name: Deploy
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/darkside.yaml
          IMAGE: ${{ needs.build.outputs.docker_image }}
